### ISSUE TITLE
Url question

### ISSUE THREAD

**Issue by JdumB** [CreeperFarm/SAO-Asuna-and-Kirito#1]
Hi there! Can I know if the --background: url() for the :root selector is only working for url hyperlink? Had try to change it to a local photo path or even css value example (background:red;) but it doesn't work. It only works if I upload the photo to a webhost and use the url hyperlink for --background: url(). Thanks

**Comment by CreeperFarm** [comment]
It only work with online image but you can use add an image to a public github repo and use https://statically.io/ to get a static link of the image and change it with the image you want

**Comment by JdumB** [comment]
I see, thank you. But is it possible to make it work with local images? The goal is to change the background by replace the image in the local folder.

**Comment by CreeperFarm** [comment]
Actually like the theme is dev, it is impossible

**Comment by JdumB** [comment]
Got it. Thanks for your time.
